config/routes.rb
Uwork::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  match '/users/:id', :to => 'users#show',    :as => :user,         :via => :get
  match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete
  get "students/show"
  get "contacts/form_empresa"
  match '/form_empresa', to:'contacts#form_empresa', via:'get'
  get "contacts/new"
  match '/contacto', to:'contacts#new', via:'get'
  get "devise/registrations/new"
  get "students/new"
  match '/postula', to:'students#new', via:'get'
  get "users/show"
  get "welcome/index"
  match '/inicio', to:'welcome#index', via:'get'
  get "welcome/empresas"
  match '/empresas', to:'welcome#empresas', via:'get'
  root :to => 'welcome#index'

  resources :contacts
  resources :students
  resources :welcome

  

end

app/models/auto.rb
class Auto < ActiveRecord::Base
end

app/models/carrera.rb
class Carrera < ActiveRecord::Base
end

app/models/colegio.rb
class Colegio < ActiveRecord::Base
end

app/models/comuna.rb
class Comuna < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/exp_laboral.rb
class ExpLaboral < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :user
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
    #validates_uniqueness_of :email
    def self.to_csv(all_students, options={})
        CSV.generate(options) do |csv|
            csv << column_names
            all_students.each do |student|
                csv << student.attributes.values_at(*column_names)
            end
        end
    end
end

app/models/trabajo_preferente.rb
class TrabajoPreferente < ActiveRecord::Base
end

app/models/universidad.rb
class Universidad < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_one :student, through: :email
	
	def self.find_for_facebook_oauth(auth)
	  where(auth.slice(:provider, :uid)).first_or_create do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    #user.firstname = auth.info.name   # assuming the user model has a name
	    #user.image = auth.info.image # assuming the user model has an image
	  end
	end
	def self.new_with_session(params, session)
	    super.tap do |user|
	      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
	        user.email = data["email"] if user.email.blank?
	      end
	    end
  	end
 	def edit
 		@user = User.find(params[:id])
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	def after_sign_in_path_for(resource)
		postula_path
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def new
		@student = Student.new
		if user_signed_in?
			@student1 = Student.find_by email:current_user.email
			#@student2 = Student.find_by_email!(current_user.email)
		end
	end

	def create
		@student = Student.create(student_params)
		if @student.save!
			redirect_to welcome_index_path, :notice => "Ya te tenemos en nuestros registros!, te contactaremos luego"
		else
			redirect_to welcome_index_path, :error => "Ups! tenemos un problema, intentalo nuevamente."
		end
	end

	def edit
	    @student = Student.find(params[:id])
	end
	def update
	    @student = Student.find(params[:id])

		if @student.update(student_params)
			redirect_to :back
		else
			render 'edit'
		end
	rescue ActionController::RedirectBackError
  			redirect_to root_path
	end
	def student_params
		params.require(:student).permit(:email, :created_at, :updated_at, :firstname, :lastname, :secondlastname, :rut,:sexo,:fechaNac,:comunaId, :hijos, :colegioId, :universidadId, :carreraId, :fechaIngreso, :duracion, :fechaEgreso, :experiencia, :experiencias, :rentaHora, :sectorId, :auto, :cel, :empresaCel, :contratoCel, :nivelIngles, :nivelAleman, :nivelPortugues, :nivelFrances, :nivelChino, :OtrosIdiomas, :marcaAuto, :anioAuto, :hobbies, :deportes)
	end

	def show
		@students = Student.find(:all)
	end

	def index
		@students = Student.find(:all)
    	respond_to do |format|
      		format.html
      		format.xls { send_data Student.to_csv(@students, col_sep: "\t") }
    	end
	end	
	def destroy
		@student = Student.find(params[:id])
		@student.destroy
		redirect_to students_show_path
	end
	
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      redirect_to postula_path
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def show
  		@users = User.find(:all)
  	end

  	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to user_path
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	  	#@student = Student.new
		#@students = Student.all
		#@contact = Contact.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_new.html.erb
<br/>
<div class="well" style="width:850px; margin-left:auto; margin-right:auto;margin-top:100px;">
  <div class="row" style="margin-left:auto; margin-right:auto; width:100%;">
    
    <div class="col-md-12">
    <div class"contacto" style="text-align:center;"><p>Puedes contactarnos enviandonos un correo a <a href="mailto:contacto@uwork.cl?Subject=Contacto%20Web" target="_top">
contacto@uwork.cl</a> ó a través de nuestro fan page en Facebook </p></div>
    <div style="margin-right:10px; margin-left:10px; padding-left:5px;padding-right:5px;">
      <div class="fb-like-box" data-href="https://www.facebook.com/699916390065576" data-width="730" data-height="600" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="true" data-show-border="false" style="margin-right:auto; margin-left:auto;"></div>
    </div>
 
</div>
</div>
</div>
</div>

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/form_empresa.html.erb
<title>Contacto Empresas - UWork</title>
<br/>
<div class="well" style="width:850px; margin-left:auto; margin-right:auto;margin-top:70px;">
  <div class="row" style="margin-left:auto; margin-right:auto; width:100%;">
    <style>
    h2.ss-section-title{
    	background-color: red;
    	color:red;
    }
    </style>
    <div class="col-md-12">
    <div class"contacto" style="text-align:center;"><p>Es necesario llenar este formulario para cada oferta de trabajo que quieras hacer llegar a nuestros postulantes, de manera de conseguir más y mejores candidatos </p></div>
    <iframe src="https://docs.google.com/forms/d/1RZfl44ZlXJidiXFt6YXGhRT42MGz3oWO7wno0zmI6o4/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Cargando...</iframe>
 
</div>
</div>
</div>
</div>

app/views/contacts/new.html.erb
<title>Contacto - UWork</title>
<div id="fb-root"></div>
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>	
<br/>
<div class="well" style="width:850px; margin-left:auto; margin-right:auto;margin-top:70px;">
  <div class="row" style="height:660px; margin-left:auto; margin-right:auto; width:100%;">
    
    <div class="col-md-12">
    <div class"contacto" style="text-align:center;"><p>Puedes contactarnos enviandonos un correo a <a href="mailto:contacto@uwork.cl?Subject=Contacto%20Web" target="_top">
contacto@uwork.cl</a> ó a través de nuestro fan page en Facebook </p></div>
    <div style="margin-right:10px; margin-left:10px; padding-left:5px;padding-right:5px;">
      <div class="fb-like-box" data-href="https://www.facebook.com/699916390065576" data-width="730" data-height="600" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="true" data-show-border="false" style="margin-right:auto; margin-left:auto;"></div>
    </div>
 
</div>
</div>
</div>
</div>

app/views/contacts/newEmpresa.html.erb
<title>Contacto Empresas - UWork</title>
<br/>
<div class="well" style="width:850px; margin-left:auto; margin-right:auto;margin-top:100px;">
  <div class="row" style="margin-left:auto; margin-right:auto; width:100%;">
    <style>
    h2.ss-section-title{
    	background-color: red;
    	color:red;
    }
    </style>
    <div class="col-md-12">
    <div class"contacto" style="text-align:center;"><p>Puedes contactarnos enviandonos un correo a <a href="mailto:contacto@uwork.cl?Subject=Contacto%20Web" target="_top">
contacto@uwork.cl</a> ó a través de nuestro fan page en Facebook </p></div>
    <iframe src="https://docs.google.com/forms/d/1RZfl44ZlXJidiXFt6YXGhRT42MGz3oWO7wno0zmI6o4/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Cargando...</iframe>
 
</div>
</div>
</div>
</div>

app/views/students/index.xls.erb
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
  	<Table>
		<Row>
			<Cell><Data ss:Type="String">Nombre</Data></Cell>
			<Cell><Data ss:Type="String">Apellido Paterno</Data></Cell>
			<Cell><Data ss:Type="String">Apellido Materno</Data></Cell>
			<Cell><Data ss:Type="String">Sexo</Data></Cell>
			<Cell><Data ss:Type="String">Rut</Data></Cell>
			<Cell><Data ss:Type="String">EMail</Data></Cell>
			<Cell><Data ss:Type="String">Cel</Data></Cell>
			<Cell><Data ss:Type="String">Empresa</Data></Cell>
			<Cell><Data ss:Type="String">Contrato</Data></Cell>
			<Cell><Data ss:Type="String">Hijos</Data></Cell>
			<Cell><Data ss:Type="String">Año Nacimiento</Data></Cell>
			<Cell><Data ss:Type="String">Comuna</Data></Cell>
			<Cell><Data ss:Type="String">Colegio</Data></Cell>
			<Cell><Data ss:Type="String">Universidad</Data></Cell>
			<Cell><Data ss:Type="String">Carrera</Data></Cell>
			<Cell><Data ss:Type="String">Ingreso</Data></Cell>
			<Cell><Data ss:Type="String">Duracion</Data></Cell>
			<Cell><Data ss:Type="String">Egreso</Data></Cell>
			<Cell><Data ss:Type="String">Ingles</Data></Cell>
			<Cell><Data ss:Type="String">Aleman</Data></Cell>
			<Cell><Data ss:Type="String">Portugues</Data></Cell>
			<Cell><Data ss:Type="String">Frances</Data></Cell>
			<Cell><Data ss:Type="String">Chino</Data></Cell>
			<Cell><Data ss:Type="String">Inicio Disponibilidad</Data></Cell>
			<Cell><Data ss:Type="String">Fin Disponibilidad</Data></Cell>
			<Cell><Data ss:Type="String">DiaHora disponible</Data></Cell>
			<Cell><Data ss:Type="String">Experiencia?</Data></Cell>
			<Cell><Data ss:Type="String">Donde?</Data></Cell>
			<Cell><Data ss:Type="String">Renta/hora</Data></Cell>
			<Cell><Data ss:Type="String">Sector preferente</Data></Cell>
			<Cell><Data ss:Type="String">Movilizacion propia</Data></Cell>
			<Cell><Data ss:Type="String">Marca</Data></Cell>
			<Cell><Data ss:Type="String">Modelo</Data></Cell>
			<Cell><Data ss:Type="String">Año</Data></Cell>
		</Row>	   
		<% @students.each do |item| %>
			<Row>
				<Cell><Data ss:Type="String"><%= item.firstname %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.lastname %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.secondlastname %> </Data></Cell>
				<Cell><Data ss:Type="String"><%= item.sexo %> </Data></Cell>
				<Cell><Data ss:Type="String"><%= item.rut %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.email %> </Data></Cell>
				<Cell><Data ss:Type="String"><%= item.cel %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.empresaCel %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.contratoCel %></Data></Cell>
				<Cell><Data ss:Type="Number"><%= item.hijos %></Data></Cell>
				<Cell><Data ss:Type="Number"><%= item.fechaNac %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.comunaId %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.colegioId %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.universidadId %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.carreraId %></Data></Cell>
				<Cell><Data ss:Type="Number"><%= item.fechaIngreso %></Data></Cell>
				<Cell><Data ss:Type="Number"><%= item.duracion %></Data></Cell>
				<Cell><Data ss:Type="Number"><%= item.fechaEgreso %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.nivelIngles %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.nivelAleman %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.nivelPortugues %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.nivelFrances %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.nivelChino %></Data></Cell>
				<Cell><Data ss:Type="Date"><%= item.dispInicio %></Data></Cell>
				<Cell><Data ss:Type="Date"><%= item.dispFin %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.dispDiaHra %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.experiencia %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.experiencias %></Data></Cell>
				<Cell><Data ss:Type="Number"><%= item.rentaHora %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.sectorId %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.auto %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.marcaAuto %></Data></Cell>
				<Cell><Data ss:Type="String"><%= item.modeloAuto %></Data></Cell>
				<Cell><Data ss:Type="Number"><%= item.anioAuto %></Data></Cell>
			</Row>
		<% end %>
	</table>
</Worksheet>
</Workbook>

app/views/students/new.html.erb
<script>
	$(document).ready( function() {
	    
	});
</script>
<br/>

	<div class="row" style="width:850px; margin-left:auto; margin-right:auto; margin-top:70px;">
		
		<div class="col-md-12">
		<% if user_signed_in? %>	
			<%#= image_tag("rss.jpg", :alt => "rss feed") %>
			<%#= auth.info.name %>
			<div style="float:right;">Sesión iniciada como <strong><%= current_user.email %></strong>. No eres tú?
				<%= link_to "Cerrar sesión", destroy_user_session_path, :method=> :delete %>
				<%= link_to "| Cambiar contraseña", edit_user_registration_path %>

			</div>

			<% if @student1 %>
				<%= render "students/editform" %>
			<% else %>
				<%= render "students/newform" %>
			<% end %>
					
			<br/>

		<% else %>
			<!--<h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Debes iniciar sesión para continuar</h3>-->
			<script type="text/javascript">
    			window.location.href="/users/sign_up"
  			</script>
			<%#= link_to "crea una cuenta", new_user_registration_path %>
		<% end %>
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<%end%>
	</div>
</div>

app/views/students/show.html.erb
<div class="pagecontainer1">
		<% if user_signed_in? %>
			<div style="float:right;">Signed in as <%= current_user.email %>. No eres tú?
				<%= link_to "Cerrar sesión", destroy_user_session_path, :method=> :delete %>
			</div>
		<h1>Personas Ingresadas</h1>
		<div style="max-height:500px;overflow:scroll;">
			<p>
			  Download:
			  <%= link_to "CSV", students_path(format: "csv") %> |
			  <%= link_to "Excel", students_path(format: "xls") %>
			</p>
				<table class="table table-stripped table-condensed" style="text-align:center color:#B7B7B7; overflow:scroll;">
					<tr style="text-align:center color:white;">
						<th>Link</th>
						<th>Creado/<br/>Editado</th>
						<th>ID</th>
						<th>Nombre<br/>Apellido1<br/>Apellido2</th>
						<th>Sexo</th>
						<th>Rut</th>
						<th>EMail</th>
						<th>Cel<br/>Empresa<br/>Contrato</th>
						<th>Hijos</th>
						<th>Año Nacimiento</th>
						<th>ComunaRegión</th>
						<th>ColegioEstudios</th>
						<th>Universidad/<br/>
							Carrera</th>
						<th>Ingreso/<br/>
							Duracion/<br/>
							Egreso</th>
						<th>Ing,Ale,Port, Fra,Chi,Otros</th>
						<th>Experiencia?</th>
						<th>Donde?</th>
						<th>Renta/hora</th>
						<th>Sector preferente</th>
						<th>Movilizacion?/<br/>
							Marca/<br/>
							Año/</th>
						<th>Hobbies</th>
						<th>Deportes</th>

					</tr>

				   
				<% if !@students.blank? %>
					<% for item in @students %>
						<tr>
							<td>
								<%= link_to 'Editar', edit_student_path(item) %>
								<%= link_to 'Borrar', student_path(item), method: :delete, data: { confirm: '¿Seguro que quieres eliminar esta entrada? 
									Luego de esta acción no hay vuelta atrás' } %>
							</td>
							<td><%= item.created_at %>
								<%= item.updated_at %>
							</td>
							<td><%= item.id %></td>
							<td><%= item.firstname %>
								<%= item.lastname %>
								<%= item.secondlastname %> </td>
							<td><%= item.sexo %> </td>
							<td><%= item.rut %></td>
							<td><%= item.email %> </td>
							<td><%= item.cel %><br/>
								<%= item.empresaCel %><br/>
								<%= item.contratoCel %></td>
							<td><%= item.hijos %></td>
							<td><%= item.fechaNac %></td>
							<td style="width:300px;"><%= item.comunaId %></td>
							<td><%= item.colegioId %></td>
							<td><%= item.universidadId %>/<br/>
								<%= item.carreraId %></td>
							<td><%= item.fechaIngreso %>/<br/>
								<%= item.duracion %>/<br/>
								<%= item.fechaEgreso %></td>
							<td><%= item.nivelIngles %><br/>
								<%= item.nivelAleman %><br/>
								<%= item.nivelPortugues %><br/>
								<%= item.nivelFrances %><br/>
								<%= item.nivelChino %><br/>
								<%= item.OtrosIdiomas %></td>
							<td><%= item.experiencia %></td>
							<td><%= item.experiencias %></td>
							<td><%= item.rentaHora %></td>
							<td><%= item.sectorId %></td>
							<td><%= item.auto %>/<br/>
								<%= item.marcaAuto %>/<br/>
								<%= item.anioAuto %></td>
							<td><%= item.hobbies %></td>
							<td><%= item.deportes %></td>
						</tr>
					<% end %>
				<% else %>
				<% end %>
			</table>
		</div>
	<% else %>
		<h3> Debes iniciar sesión para continuar</h3>
		<h5>Si ya tienes una cuenta, haz click 
		<%= link_to "acá", new_user_session_path %> ó
		<%= link_to "crea una cuenta", new_user_registration_path %>
		</h5>
	<% end %>
	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<%end%>
</div>

app/views/users/show.html.erb
<div class="pagecontainer1">
		<% if user_signed_in? %>
			<div style="float:right;">Signed in as <%= current_user.email %>. No eres tú?
				<%= link_to "Cerrar sesión", destroy_user_session_path, :method=> :delete %>
			</div>
		<h1>Usuarios Ingresados</h1>
		<div style="max-height:500px;overflow:scroll;">
				<table class="table table-stripped table-condensed" style="text-align:center color:#B7B7B7; overflow:scroll;">
					<tr style="text-align:center color:white;">
						<th>links</th>
						<th>ID</th>
						<th>Email</th>
						<th>Reset password sent at</th>
						<th>Sign in count</th>
						<th>Current sign in at</th>
						<th>Current sign in IP</th>
						<th>Last sign in at</th>
						<th>last sign in IP</th>
						<th>Created at</th>
						<th>Updated at</th>
						<th>Type</th>
					</tr>

				<% if !@users.blank? %>
					<% for item in @users %>
						<tr>
							<td>
								<%#= link_to 'Editar', edit_user_path(item) %>
								<%= link_to 'Borrar', user_path(item), method: :delete, data: { confirm: '¿Seguro que quieres eliminar esta entrada? 
									Luego de esta acción no hay vuelta atrás' } %>
								<%= link_to "Editar", edit_user_registration_path(item) %>
							</td>
							<td><%= item.id %></td>
							<td><%= item.email %></td>
							<td><%= item.reset_password_sent_at %></td>
							<td><%= item.sign_in_count %></td>
							<td><%= item.current_sign_in_at %> </td>
							<td><%= item.current_sign_in_ip %></td>
							<td><%= item.last_sign_in_at %> </td>
							<td><%= item.last_sign_in_ip %><br/>
							<td><%= item.created_at %><br/>
							<td><%= item.updated_at %></td>
							<td><%= item.type %></td>
						</tr>
					<% end %>
				<% else %>
				<% end %>
			</table>
		</div>
	<% else %>
		<h3> Debes iniciar sesión para continuar</h3>
		<h5>Si ya tienes una cuenta, haz click 
		<%= link_to "acá", new_user_session_path %> ó
		<%= link_to "crea una cuenta", new_user_registration_path %>
		</h5>
	<% end %>
	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<%end%>
</div>

app/views/welcome/empresas.html.erb
<br/>
<div class="well" style="width:1000px; margin-left:auto; margin-right:auto;margin-top:70px;">
  <div class="row" style="margin-left:auto; margin-right:auto; width:100%;">
    <style>
    h2.ss-section-title{
        background-color: red;
        color:red;
    }
    </style>
    <div class="col-md-12">     
        <div style="width:980px;">
            <p class="p1">
                Contáctate con nosotros para que te entreguemos los planes de nuestro servicio.
            </p>
            <p class="p2">
                Te aseguramos el mejor precio del mercado y los mejores candidatos para que realicen tu trabajo!
            </p>
            <p class="p3">
                Envíanos un email a <a href="mailto:contacto@uwork.cl">contacto@uwork.cl</a>
            </p>
            <p>
            <br></p>
            <div class="row">
                <div class="span3">
                    <p class="p10">
                        ¿quiénes somos?
                    </p>
                    <p class="p4">
                        <span style="font-size:115%">
                            <span style="color:#0088cc">uwork</span> es una bolsa de trabajo que está 100% enfocada en estudiantes.</span><br> De esta forma facilitamos a las empresas en la búsqueda de candidatos para trabajos part time o esporádicos.
                    </p>
                </div>
                <div class="span3">
                    <p class="p10">
                        ¿qué tenemos?
                    </p>
                    <p class="p4">
                        <span style="font-size:115%">Nuestros postulantes son tan variados como profesiones hay en el país.</span><br>
                        Si se busca gente para trabajar con niños… <span style="color:#0088cc">lo contactamos con estudiantes de párvulos.</span><br>
                        Si se busca promotores de tecnología… <span style="color:#0088cc">contamos con estudiantes de informática…</span><br>
                        Si se busca garzones, personal para catering, matrimonios y similares… <span style="color:#0088cc">les presentamos a estudiantes de gastronomía.</span><br>    
                        Si no requiere un estudiante de una carrera específica, y solo requiere experiencia    previa en su rubro… <span style="color:#0088cc">LE AYUDAREMOS CON ESOS CONTACTOS!</span>
                    </p>
                </div>
                <div class="span3">
                    <p class="p10">
                        ¿por qué elegirnos?
                    </p>
                <p class="p4">
                    <span style="font-size:115%">A diferencia del sistema tradicional, nosotros ya contamos con una creciente base de datos de estudiantes y no debemos buscarlos, por lo que el proceso de selección de candidatos es inmediato.</span><br>
                    Seleccionamos utilizando filtros, para ajustar el perfil del candidato a las necesidades específicas de tu empresa.
                </p>
            </div>
        </div>
        <p><br></p>
        <p><br></p>
    </div>
    <!--<div class"contacto" style="padding: 50px; font-size: 120%;text-align:center; height:500px;"><p>Contáctate con nosotros para que te entreguemos los planes de nuestro servicio. Te aseguramos el mejor precio del mercado y los mejores candidatos estudiantes para que realizen tu trabajo!.
    Puedes enviarnos un email a contacto@uwork.cl </p></div>-->
 
</div>
</div>
</div>
</div>